
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '12.19.0'    
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and run
    - run: npm install
    - run: npm run build --if-present

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: production
    concurrency: production

    steps:
    - name: 'run'
    - run: npm run www -- --port 443 --if-present
